# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:14:52+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Groups(BaseModel):
    kind: Optional[str] = Field(
        None, description='The kind of insert resource this is.'
    )
    responseCode: Optional[str] = Field(
        None, description='The status of the insert request.'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'
